image: continuumio/miniconda3:latest

stages:
  - test

test:
  stage: test
  # tags: 
  #   - linux

  script:
    - conda install mamba -c conda-forge
    - mamba env create -n geokit --file=requirements-dev.yml
    - conda info --envs
    - conda activate geokit
    - python -m pip install -e . --no-deps
    - python -m pytest --cov=geokit geokit/test/
