image: mambaorg/micromamba

stages:
  - test

.test_template:
  stage: test
  before_script:
    # create environment
    - micromamba create -y -n geokit --file=requirements-dev.yml
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate geokit
    # Install geokit with no --no-deps flag to create a reproducible environment
    - python -m pip install -e . --no-deps

test-code:
  extends: .test_template
  script:
    # Test code
    - python -m pytest --cov=geokit geokit/test/

  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
