image: continuum/miniconda3:latest

stages:
  - test

test:
  stage: test

  script: 
    - conda install mamba -c conda-forge
    - mamba env update -n geokit --file=requirements.yml
    - mamba env update -n geokit --file=requirements-dev.yml
    - mamba info --envs
    - source activate geokit
    - python -m pip install -e .
    - python -m pytest --cov=geokit geokit/test/
