image: continuumio/miniconda3:latest

stages:
  - test

test:
  stage: test
  # tags: 
  #   - linux

  script:
    # Install Mamba for faster installation
    - conda install mamba -c conda-forge
    # Install dependecies from environment file
    - mamba env create -n geokit --file=requirements-dev.yml
    - conda info --envs
    - source activate geokit
    # Install geokit with no --no-deps flag to create a reproducible environment
    - python -m pip install -e . --no-deps
    # Test Environment
    - python -m pytest --cov=geokit geokit/test/
