[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "geokit"
version = "1.9.0"
description = "Geokit is a library that interfaces with GDAL to support general-purpose geospatial data analysis with a focus on raster-vector interoperability."
authors = [
  { name = "David Severin Ryberg" },
  { name = "Christoph Winkler", email = "c.winkler@fz-juelich.de" },
  { name = "Ishmam Shitab", email = "s.ishmam@fz-juelich.de" },
  { name = "Julian Belina", email = "j.belina@fz-juelich.de" },
]
maintainers = [
  { name = "Julian Belina", email = "j.belina@fz-juelich.de" },
  { name = "Ishmam Shitab", email = "s.ishmam@fz-juelich.de" },
]
license = { file = "LICENSE.txt" }
readme = "README.md"


[tool.hatch.build.targets.wheel]
packages = ["geokit"]


[tool.hatch.build.targets.sdist]
include = ["/geokit", "/Examples", "/test", "/README.md", "/LICENSE.txt"]

#Configuration options
# https://docs.pytest.org/en/7.1.x/reference/reference.html#configuration-options

[tool.pytest.ini_options]
testpaths = ["test"] # Sets the path where to look for tests
pythonpath = [
  "test",
] # Sets the path which should be prepended to pythonpath relative to the root folder
console_output_style = "count"
filterwarnings = [
  "ignore:This process.*is multi-threaded.*fork:DeprecationWarning:multiprocessing.popen_fork",
]
typeguard-packages = """
geokit"""
typeguard-debug-instrumentation = true
typeguard-forward-ref-policy = "ERROR"
typeguard-collection-check-strategy = "ALL_ITEMS"

[tool.docformatter]
recursive = true
wrap-summaries = 120
blank = true

[tool.codespell]
ignore-words-list = ["subTiles", "fo", "uite"]

[tool.pydocstyle]
convention = "numpy"
