name: geokit_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  # - python
  # - pytest
  # - pytest-cov
  # - pylint
  # - autopep8
  # - jupyter
  # - notebook
  # - jupyterlab
  - matplotlib 
  - pandas 
  - numpy 
  - descartes 
  - scipy 
  - scikit-learn 
  - gdal
  - smopy 
  - geopandas 
  - pooch 
  - structlog 
  - rich 
  - psutil 
