name: geokit
channels:
  - conda-forge
dependencies:
  # - python
  # - pytest
  # - pytest-cov
  # - pylint
  # - autopep8
  # - jupyter
  # - notebook
  # - jupyterlab
  - pip
  - matplotlib
  - descartes
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - gdal>=2.4.0, !=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*
  - iek-3::smopy
  - pip:
      - .
