name: Code Improvement
description: Propose improvement to the code
type: 'Docs'

body:
- type: textarea
  id: Purpose
  attributes:
    label: Purpose of the improvement
    description: >
      How should your proposal improve the code?
      - Increase efficiency
      - Improve maintainability
      - Improve the user interaction e.g. remove warnings
  validations:
    required: true
- type: textarea
  id: Proposal
  attributes:
    label: Proposal
    description: >
      Please provide a description of what should be improved.
  validations:
    required: true