on:
  pull_request:
    branches: ["master"]

jobs:
  TestPushCondaForgeDev:
    name: Test conda-forge development version on ${{ matrix.runner_tag }} for gdal=${{ matrix.gdal_version }}
    strategy:
      fail-fast: false
      matrix:
        runner_tag:
          [
            "ubuntu-24.04",
            "ubuntu-22.04",
            "macos-13",
            "macos-14",
            "macos-15",
            "windows-2025",
            "windows-2022",
          ]
        gdal_version:
          [
            "3.10.0",
            "3.10.1",
            "3.10.2",
            "3.10.3",
            "3.9.0",
            "3.9.1",
            "3.9.2",
            "3.9.3",
            "3.4.2",
            "3.4.3",
          ]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      requirements_file_name: requirements-dev.yml
      ipynb_example_folder: "Examples"
      library_name: "gdal"
      library_version: ${{ matrix.gdal_version }}
      dependency_position_env_file: "9"
