name: Check code formatting and Linter hints

on: [ push, pull_request ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - name: Check Linter
        run: ruff check --output-format=github .
      - name: Check Format
        run: ruff format --check  