name: Test Geokit 1.3.0 for scikit-learn Versions
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual run' 
  push:
    branches: 
      - version/1.3.0
  # Allows to trigger the workflow manually
    
jobs:
    TestGeokitForNumpyVersions:
        name: scikit-learn=${{ matrix.scikit_learn_version }},${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
                # os: ["ubuntu-latest","ubuntu-20.04", "macos-latest","macos-13","macos-12", "macos-11","windows-latest","windows-2019"]
                os: ["ubuntu-latest"]
                geokit_version: ["1.3.0"]               
                # scikit_learn_version: ["1.4.2","1.4.1","1.4.1","1.4.0","1.3.2","1.3.1","1.3.0",
                scikit_learn_version: ["1.2.2","1.2.1","1.2.0","1.1.3","1.1.2","1.1.1","1.1.0","0.24.2","0.24.1","0.24.0","0.23.2","0.23.1","0.23.1","0.23.0","0.22.1","0.22","0.21.3","0.21.2","0.21.1","0.21.0","0.20.4","0.20.3","0.20.2","0.20.1","0.20.0","0.19.2","0.19.1","0.19.0","0.18.2","0.18.1","0.18.0","0.18","0.17"] 
        steps:
            - name: Setup Conda
              uses: conda-incubator/setup-miniconda@v3
              with:
                miniforge-version: latest
                channels: conda-forge,nodefaults
                activate-environment: test_env
                conda-remove-defaults: "true"
            - name: Checkout geokit
              uses: actions/checkout@v4
              with:
                repository: FZJ-IEK3-VSA/geokit
                fetch-depth: 0   
                ref: version/1.3.0        
            - name: Update values.yaml
              uses: fjogeleit/yaml-update-action@main
              with:
                valueFile: 'requirements-dev.yml'
                commitChange: false
                method: CreateOrUpdate
                changes: |
                  {
                  "dependencies[14]": "scikit-learn=${{ matrix.scikit_learn_version }}"
                  }
            - name: Install libraries
              shell: pwsh
              id: install-step
              run: |
                    ls
                    echo "LS Done"
                    conda config --add channels nodefaults -conda-forge
                    mamba env create --file=requirements-dev.yml -c conda-forge -c nodefaults -n test_env 
                    conda run -n test_env python pip install -e . --no-deps
                    echo "Installation done"
                    conda list -n test_env
                    echo "libraries printed" 
            - name: Run pytest for geokit
              shell: pwsh
              run: |
                    echo "Start ls"
                    ls
                    echo "ls terminated"
                    cd geokit
                    ls
                    echo "Second ls terminated"
                    echo "start pytest"
                    conda run -n test_env python -m pytest
                    echo "Pytest done"
