name: Test Geokit 1.4.1 for Python Versions
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual run' 
  push:
    branches: 
      - version/1.4.1
  # Allows to trigger the workflow manually
    
jobs:
    TestGeokitForNumpyVersions:
        name: python=${{ matrix.python_version }},${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
                # Min
                # os: ["ubuntu-24.04"]
                # All tested
                os: ["ubuntu-24.04","ubuntu-22.04", "macos-13","macos-14","macos-15","windows-2025","windows-2022"]
                # Not tested because it fails on gdal
                # os: ["macos-14","macos-15"]
                # Proper version
                python_version: ["3.8","3.9","3.10"]
                # Failing version
                # python_version: ["3.7","3.11"] 
        steps:
            - name: Setup Conda
              uses: conda-incubator/setup-miniconda@v3
              with:
                miniforge-version: latest
                channels: conda-forge,nodefaults
                activate-environment: test_env
                conda-remove-defaults: "true"
            - name: Checkout geokit
              uses: actions/checkout@v4
            - name: Update values.yaml
              uses: fjogeleit/yaml-update-action@main
              with:
                valueFile: 'requirements-dev.yml'
                commitChange: false
                method: CreateOrUpdate
                changes: |
                  {
                  "dependencies[0]": "python =${{ matrix.python_version }}"
                  }
            - name: Install libraries
              shell: pwsh
              id: install-step
              run: |
                    ls
                    echo "LS Done"
                    conda config --add channels nodefaults conda-forge
                    mamba env create --file=requirements-dev.yml -c conda-forge -c nodefaults -n test_env 
                    conda run -n test_env python pip install -e . --no-deps
                    echo "Installation done"
                    conda list -n test_env
                    echo "libraries printed" 
            - name: Run pytest for geokit
              shell: pwsh
              run: |
                    echo "Start ls"
                    ls
                    echo "ls terminated"
                    cd geokit
                    ls
                    echo "Second ls terminated"
                    echo "start pytest"
                    conda run -n test_env python -m pytest
                    echo "Pytest done"
