name: Check code formatting and Linter hints

on: [ push, pull_request ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - name: Check Linter
        run: ruff check --output-format=github . --config ruff.toml
      - name: Check Linter for .ipynb files
        run: nbqa ruff Examples --config ruff.toml
      - name: Check Format
        run: ruff format --check --config ruff.toml